// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thvdtawekohgjtbvrjcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodmR0YXdla29oZ2p0YnZyamNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NjUxODYsImV4cCI6MjA1MzI0MTE4Nn0.Ba6QjdXH4PJYiuVV-rm4mvzPF89mrK8QsKovz_34ugE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);